#!/usr/bin/env perl
# vim:ts=4:sw=4:expandtab
# © 2010-2011 Michael Stapelberg (see also: LICENSE)
# © 201x Simon Elsbrock
# © 201x Maik Fischer

use v5.14;
use warnings FATAL => 'all';
use Getopt::Long;
use FindBin;
use lib "$FindBin::Bin/../lib";
use RaumZeitChef;

my %options = (
    server => 'irc.hackint.net',
    port => 6667,
    nick => 'RaumZeitChef',
    channel => '#raumzeitlabor',
    nickserv_pw => delete $ENV{IRCBOT_CHEF_NICKSERV}, # export in /etc/default/ircbot-chef
);

GetOptions(
    'nick=s' => \$options{nick},
    'channel=s' => \$options{channel},
    'server=s' => \$options{server},
    'port=i' => \$options{port},
    'version' => sub {
        say "ircbot-chef v$RaumZeitChef::VERSION";
        exit 0;
    },
    'help' => sub {
        say "ircbot-chef: no options, started via initscript.";
        exit 0;
    }
);

RaumZeitChef->new(%options)->run();
