#!/usr/bin/env perl
# vim:ts=4:sw=4:expandtab
# © 2010-2011 Michael Stapelberg (see also: LICENSE)
# © 201x Simon Elsbrock
# © 201x Maik Fischer

use v5.14;
use warnings FATAL => 'all';
use Getopt::Long;
use FindBin;
use lib "$FindBin::Bin/../lib";
use RaumZeitChef;
use RaumZeitChef::Config;

# defaults are in RaumZeitChef::Config
my %options;

GetOptions(\%options,
    'nick=s',
    'channel=s',
    'server=s',
    'port=i',
    'version' => sub {
        say "ircbot-chef v$RaumZeitChef::VERSION";
        exit 0;
    },
    'help' => sub {
        say "ircbot-chef: no options, started via initscript.";
        exit 0;
    }
);

my $config = RaumZeitChef::Config->new(%options);

RaumZeitChef->new(config => $config)->run();
