#!/usr/bin/env perl
# vim:ts=4:sw=4:expandtab
# © 2010-2011 Michael Stapelberg (see also: LICENSE)
#
# This script is an IRC bot (RaumZeitMPD) which displays the currently playing
# song (querying the MPD) upon !stream and enables a light upon !ping.
#

use strict;
use warnings;
use feature qw(say);
use Getopt::Long;
use FindBin;
use lib "$FindBin::Bin/../lib";
use RaumZeitLabor::IRC::MPD;

GetOptions(
    'version' => sub {
        say "ircbot-mpd v$RaumZeitLabor::IRC::MPD::VERSION";
        exit 0;
    },
    'help' => sub {
        say "ircbot-mpd: no options, started via initscript.";
        exit 0;
    }
);

RaumZeitLabor::IRC::MPD->run();
